### ISSUE TITLE
Error when reading labels

### ISSUE THREAD

**Issue by bobzub** [crobird/wave_markers#1]
Hello,

I own a morphagene and saw your post on muffwiggler about your script.

I am not good at coding.

I was receiving this error when trying to run your script on a wav file with a label file:

Traceback (most recent call last):
  File "./add_markers.py", line 52, in <module>
    main(args)
  File "./add_markers.py", line 31, in main
    wave_labels = get_wave_labels(w.rate, args.labelfile)
  File "./add_markers.py", line 23, in get_wave_labels
    (start, end, label) = line.strip().split("\t")
ValueError: need more than 2 values to unpack

It seems it is actually looking for 3 values rather than 2 (start, end, label).

The label file generated by audacity only contains 2 values per line:

0.000000        2.728952
2.728952        8.256069
8.256069        12.042985
12.042985       12.784548
12.784548       14.386324
14.386324       15.068562
15.068562       16.284726
16.284726       19.676141
19.676141       24.056307
24.056307       31.471938
31.471938       32.124514
32.124514       34.635941
34.635941       41.001271

I did not see any interesting options when exporting the labels in audacity. When I created the labels I did give each one a "name", using a, b, c, d, etc, for the names. Maybe I am missing something here?

In the end I added a third column by hand, with the label names, to my label file (maybe you can put any value in there??):

0.000000        2.728952        a
2.728952        8.256069        b
8.256069        12.042985       c
12.042985       12.784548       d
12.784548       14.386324       e
14.386324       15.068562       f
15.068562       16.284726       g
16.284726       19.676141       h
19.676141       24.056307       i
24.056307       31.471938       j
31.471938       32.124514       k
32.124514       34.635941       l
34.635941       41.001271       m

I then reran the script and it worked! I was able to copy the created wav file onto my SD card, load it up in the morphagene, and it totally works with the splices.

Not sure what I missed, if anything. I figured I would add this comment in case it is helpful.

**Comment by crobird** [comment]
This is super helpful, thanks! Looks like I didn't consider the possibility that the marker file wouldn't have label names, should be an easy fix to make.

**Comment by crobird** [comment]
I've committed an update to the add_markers.py that should hopefully address the issue. The Audacity (version 2.1.3) on my mac outputs a file with 3 columns.

Let me know if this doesn't end up working on your end.
